import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Next.js - Starter Template</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="grid w-screen h-screen place-items-center">
                Welcome to NextJS Starter Template
            </div>
        </div>
    );
};

export default Home;
